# Generated by Django 4.2.1 on 2023-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('male_description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О насы',
            },
        ),
    ]
