# Generated by Django 4.2.1 on 2023-11-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='male_description',
            new_name='description',
        ),
    ]
