# Generated by Django 4.2.1 on 2023-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_male_description_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teammembers/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('profession', models.CharField(max_length=30, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Член Команды',
                'verbose_name_plural': 'Члены Команды',
            },
        ),
    ]
